# Importing Numpy Library

In [1]:
import numpy as np

# Matrix Addition

## Two matrices can be added only if they have the same shape

In [2]:
# creating two(2) matrices
a = np.array([[2,3], [4,5]])
b = np.array([[6,7], [8,9]])

In [4]:
print(a)

[[2 3]
 [4 5]]


In [5]:
print(b)

[[6 7]
 [8 9]]


In [6]:
a.shape
b.shape

(2, 2)

# Adding two(2) matrices

In [7]:
sum = a + b

In [8]:
print(sum)

[[ 8 10]
 [12 14]]


# Creating two(2) matrices with random values

In [9]:
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [10]:
print(matrix_1)

[[0 9 4]
 [9 6 8]
 [0 1 5]]


In [11]:
print(matrix_2)

[[ 7  2  0]
 [ 0 19  9]
 [ 9 11 13]]


In [12]:
sum = np.add(matrix_1, matrix_2)

In [13]:
print(sum)

[[ 7 11  4]
 [ 9 25 17]
 [ 9 12 18]]


In [15]:
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [16]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

# Matrix Subtraction

In [17]:
# creating two(2) matrices
a = np.array([[2,3], [4,5]])
b = np.array([[6,7], [8,9]])

In [18]:
print(a)

[[2 3]
 [4 5]]


In [19]:
print(b)

[[6 7]
 [8 9]]


In [20]:
a.shape
b.shape

(2, 2)

# Subtracting two(2) vectors

In [21]:
difference = a - b

In [22]:
print(difference)

[[-4 -4]
 [-4 -4]]


# Creating two(2) matrices with random values

In [23]:
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [24]:
print(matrix_1)

[[6 9 2]
 [4 4 9]
 [9 5 8]]


In [25]:
print(matrix_2)

[[16 11 19]
 [15 18  1]
 [ 6 15 15]]


In [26]:
difference = np.subtract(matrix_1, matrix_2)

In [27]:
print(difference)

[[-10  -2 -17]
 [-11 -14   8]
 [  3 -10  -7]]


# Multiplying a matrix by a scaler

In [28]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[6 8 5 1]
 [4 7 1 2]
 [6 5 3 1]
 [2 4 3 5]]


In [29]:
product = np.multiply(x,y)
print(product)

[[30 40 25  5]
 [20 35  5 10]
 [30 25 15  5]
 [10 20 15 25]]


# Multiplying Two(2) matrices

In [34]:
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [36]:
print(matrix_3)

[[2 4 3]
 [1 2 3]
 [1 3 3]]


In [37]:
print(matrix_4)

[[0 2 0 1]
 [3 1 3 1]
 [3 1 3 1]]


In [39]:
product = np.dot(matrix_3, matrix_4)
print(product)

[[21 11 21  9]
 [15  7 15  6]
 [18  8 18  7]]


In [40]:
product.shape

(3, 4)

In [43]:
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [44]:
product = np.dot(matrix_3, matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)