# Import Numpy Library

In [1]:
import numpy as np

# Creating a Matrix using Numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10,20,30],[2,4,6],[12,22,32]])
print(matrix_2)

[[10 20 30]
 [ 2  4  6]
 [12 22 32]]


In [6]:
matrix_2.shape

(3, 3)

# Creating Matrices with Random Values

In [7]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.90048875 0.69200747 0.63466934]
 [0.79914754 0.26448488 0.27354746]
 [0.22815103 0.64794509 0.18652063]]


# Creating Matrices with Random Integers

In [8]:
random_matrix_integers = np.random.randint(100, size=(4,5))
print(random_matrix_integers)

[[ 8 10 24 98 32]
 [34 60 68 13 36]
 [89 28 32 84 89]
 [71 90 67 72 76]]


# Matrix with all the values as 1

In [9]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [11]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


# Null or Zero Matrix

In [12]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# Identity of Matrix

In [15]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
identity_matrix = np.eye(10,10)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Transpose of a Matrix

## Matrix with Random Integers

In [17]:
a = np.random.randint(100, size=(4,5))
print(a)

[[72 99  7 87 67]
 [40 41 14 30  6]
 [79 74 87 29 77]
 [75 15 80 20 30]]


In [18]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[72 40 79 75]
 [99 41 74 15]
 [ 7 14 87 80]
 [87 30 29 20]
 [67  6 77 30]]
